# AUTOGENERATED! DO NOT EDIT! File to edit: 02_application.ipynb (unless otherwise specified).

__all__ = ['create_app']

# Cell
from flask import Flask

def create_app():
    app = Flask(__name__)
    return app