# AUTOGENERATED! DO NOT EDIT! File to edit: 04_database.ipynb (unless otherwise specified).

__all__ = ['DatabaseSettings', 'create_mlb_engine']

# Internal Cell

from pydantic import BaseSettings,Field
from typing import Optional
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

# Cell

class DatabaseSettings(BaseSettings):
    username: str
    password: str
    host: str
    drivername: str
    database: str = 'MLB'

    class Config:
        env_file = '.env'
        env_prefix:str = 'db_'

# Cell

def create_mlb_engine():
    settings = DatabaseSettings()

    engine = create_engine(
        URL(**settings.dict())
    )
    return engine