# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Database": "00_core.ipynb",
         "cached_query": "00_core.ipynb",
         "Database.cached_query": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://humblechuck.github.io/sql_s3/"

git_url = "https://github.com/humblechuck/sql_s3/tree/master/"

def custom_doc_links(name): return None
